services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres         
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: postgres       
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_started  
    env_file:
      - .env      
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload